name: Build & Release GC goteth scraper

on:
    # pull_request:
    #   types: [ closed ]
    push:
      branches:
        - master

concurrency:
  group: gc-goteth-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    
    # if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Get Organization Name
        id: org_name
        run: |
          org_name=$(echo "${{ github.repository_owner }}")
          echo "Organization Name: $org_name"
          echo "org_name=$org_name" >> $GITHUB_OUTPUT

      - name: Extract commit
        id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          use: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ steps.org_name.outputs.org_name }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Latest
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ steps.org_name.outputs.org_name }}/goteth:latest \
            --push .
  
      - name: Push Versioned
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ steps.org_name.outputs.org_name }}/goteth:${{ steps.commit.outputs.short }} \
            --push .
            
